# Рабочая тетрадь 2
## Лищенко Т.В. ИМБО-01-22

1.1. Теоретический материал – Библиотека NumPy
=
<p> NumPy (NumericalPython) - это библиотека Python с открытым
исходным кодом, которая используется практически во всех областях науки
и техники. Это универсальный стандарт для работы с числовыми данными в
Python.</p>
    <p>Если у вас уже есть Python, вы можете установить NumPy с помощью
командной строки: </p>

```pip install numpy```

<p>Чтобы начать использовать NumPy необходимо импортировать
соответствующую библиотеку:</p>


```import numpy as np```

<p>Основным объектом NumPy является однородный многомерный
массив (в numpy называется numpy.ndarray). Это многомерный массив
элементов (обычно чисел), одного типа.</p>
   <p> Наиболее важные атрибуты объектов ndarray: </p>


>ndarray.ndim - число измерений (чаще их называют "оси") массива.

>ndarray.shape - размеры массива, его форма. Это кортеж натуральных
чисел, показывающий длину массива по каждой оси. Для матрицы из n строк
и m столбов, shape будет (n,m). Число элементов кортежа shape равно ndim.

>ndarray.size - количество элементов массива. Очевидно, равно
произведению всех элементов атрибута shape.

>ndarray.dtype - объект, описывающий тип элементов массива. Можно
определить dtype, используя стандартные типы данных Python. NumPy здесь
предоставляет целый букет возможностей, как встроенных, например: bool_,
character, int8, int16, int32, int64, float8, float16, float32, float64, complex64,
object_, так и возможность определить собственные типы данных, в том
числе и составные.

>ndarray.itemsize - размер каждого элемента массива в байтах.

>ndarray.data - буфер, содержащий фактические элементы массива.

<p>Обычно не нужно использовать этот атрибут, так как обращаться к
элементам массива проще всего с помощью индексов.</p>
<p>Подробнее о массивах в NumPy можно найти в официальной документации </p> 

>[Ссылка на документацию](https://numpy.org/doc/stable/user/absolute_beginners.html)

### 1.2.1 Пример

In [1]:
import numpy as np

In [5]:
x = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10]])
x, x[3][1], x[1]

(array([[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]]),
 8,
 array([3, 4]))

### 1.2.2 Пример

In [6]:
a = np.zeros(10)
b = np.ones(10)
c = np.full(10, 5)
d = np.arange(10, 20)
print(a, '\n', b, '\n', c, '\n', d)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] 
 [5 5 5 5 5 5 5 5 5 5] 
 [10 11 12 13 14 15 16 17 18 19]


### 1.2.3 Пример

In [9]:
Z = np.random.random((10,10))
Zmin, Zmax, Zmean = Z.min(), Z.max(), Z.mean()
print(Zmin, Zmax, Zmean)

0.014621902147009425 0.992222124621009 0.536154245116384


### 1.2.4 Пример

In [44]:
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
A

array([[ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [14]:
0 * np.nan,  np.nan == np.nan, np.inf > np.nan, np.nan - np.nan, 0.3 == 3 * 0.1


(nan, False, False, nan, False)

### 1.2.5 Пример

In [16]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

### 1.3.1 Задание

In [24]:
x = np.zeros((8, 8), dtype = int)
x[1::2, ::2] = 1
x[::2, 1::2] = 1
for i in range(8):
    for j in range(8):
        print(x[i][j], end =" ")
    print()

0 1 0 1 0 1 0 1 
1 0 1 0 1 0 1 0 
0 1 0 1 0 1 0 1 
1 0 1 0 1 0 1 0 
0 1 0 1 0 1 0 1 
1 0 1 0 1 0 1 0 
0 1 0 1 0 1 0 1 
1 0 1 0 1 0 1 0 


### 1.3.2 Задание

In [42]:
A = np.zeros((5,5))
A += np.arange(5)
for i in range(5):
    for j in range(5):
        print(int(A[i][j]), end =" ")
    print()

0 1 2 3 4 
0 1 2 3 4 
0 1 2 3 4 
0 1 2 3 4 
0 1 2 3 4 


### 1.3.3 Задание

In [36]:
arr = np.random.random((3,3,3))
arr

array([[[0.0295635 , 0.53548179, 0.90097518],
        [0.65030574, 0.27198231, 0.90353119],
        [0.23786011, 0.47726528, 0.24588526]],

       [[0.3325448 , 0.09470693, 0.74413688],
        [0.37979085, 0.13410515, 0.6926233 ],
        [0.07871064, 0.33306587, 0.71120901]],

       [[0.4781667 , 0.59618221, 0.90730409],
        [0.7376802 , 0.18782049, 0.22914692],
        [0.81356762, 0.59459168, 0.72077795]]])

### 1.3.4 Задание

In [41]:
x = np.ones((5,5))
x[1:-1, 1:-1] = 0
for i in range(5):
    for j in range(5):
        print(int(x[i][j]), end =" ")
    print()

1 1 1 1 1 
1 0 0 0 1 
1 0 0 0 1 
1 0 0 0 1 
1 1 1 1 1 


### 1.3.5 Задание

In [59]:
arr = np.random.randint(1, 10, 10)
arr[::-1].sort()
arr

array([8, 7, 7, 6, 6, 3, 2, 1, 1, 1])

### 1.3.6 Задание

In [72]:
x = np.zeros((5,5))
x += np.random.randint(1, 10, 5)
for i in range(5):
    for j in range(5):
        print(int(x[i][j]), end =" ")
    print()
x.size, x.shape

6 2 4 1 4 
6 2 4 1 4 
6 2 4 1 4 
6 2 4 1 4 
6 2 4 1 4 


(25, (5, 5))